// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBahPCzPOwsxEEinx8n6gAOHAPABQfAS7s",
    authDomain: "doggy-training-51e3d.firebaseapp.com",
    projectId: "doggy-training-51e3d",
    storageBucket: "doggy-training-51e3d.firebasestorage.app",
    messagingSenderId: "451937564533",
    appId: "1:451937564533:web:ea4f784b31d479a737c53c",
    measurementId: "G-7LPLJXHWNF"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnEWkE9JJkKXUIdlNnsPjmyvBBpHXxpNQ',
    appId: '1:451937564533:android:6561cc7e52a3373337c53c',
    messagingSenderId: '451937564533',
    projectId: 'doggy-training-51e3d',
    storageBucket: 'doggy-training-51e3d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6hGr0T1oxGndtlxQmdmJvvZa3vKvou3o',
    appId: '1:451937564533:ios:b4a7c8ac262993f037c53c',
    messagingSenderId: '451937564533',
    projectId: 'doggy-training-51e3d',
    storageBucket: 'doggy-training-51e3d.firebasestorage.app',
    iosBundleId: 'com.example.dogTrainingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6hGr0T1oxGndtlxQmdmJvvZa3vKvou3o',
    appId: '1:451937564533:ios:b4a7c8ac262993f037c53c',
    messagingSenderId: '451937564533',
    projectId: 'doggy-training-51e3d',
    storageBucket: 'doggy-training-51e3d.firebasestorage.app',
    iosBundleId: 'com.example.dogTrainingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBahPCzPOwsxEEinx8n6gAOHAPABQfAS7s',
    appId: '1:451937564533:web:70ec4d573834898937c53c',
    messagingSenderId: '451937564533',
    projectId: 'doggy-training-51e3d',
    authDomain: 'doggy-training-51e3d.firebaseapp.com',
    storageBucket: 'doggy-training-51e3d.firebasestorage.app',
    measurementId: 'G-D3WV53L5WE',
  );

}