// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS1G9xDZW2uRXoBEiIjXpEG5Z52gAfOmg',
    appId: '1:527653732367:web:2423dd90eda5df9a20237a',
    messagingSenderId: '527653732367',
    projectId: 'datadoggy-43c89',
    authDomain: 'datadoggy-43c89.firebaseapp.com',
    storageBucket: 'datadoggy-43c89.firebasestorage.app',
    measurementId: 'G-TRNVSJYYH8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCID_eXhLWhMaDRb0VIdLgSjWkzL6xozGE',
    appId: '1:527653732367:android:34b84b5a8f72400020237a',
    messagingSenderId: '527653732367',
    projectId: 'datadoggy-43c89',
    storageBucket: 'datadoggy-43c89.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9CDoK1FzBGpbRGpTlp1-kL2OMMH1QbNQ',
    appId: '1:527653732367:ios:c19ed9bd01b06ab120237a',
    messagingSenderId: '527653732367',
    projectId: 'datadoggy-43c89',
    storageBucket: 'datadoggy-43c89.firebasestorage.app',
    iosBundleId: 'com.example.dogTrainingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9CDoK1FzBGpbRGpTlp1-kL2OMMH1QbNQ',
    appId: '1:527653732367:ios:c19ed9bd01b06ab120237a',
    messagingSenderId: '527653732367',
    projectId: 'datadoggy-43c89',
    storageBucket: 'datadoggy-43c89.firebasestorage.app',
    iosBundleId: 'com.example.dogTrainingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBS1G9xDZW2uRXoBEiIjXpEG5Z52gAfOmg',
    appId: '1:527653732367:web:1c5ede0861fdec2620237a',
    messagingSenderId: '527653732367',
    projectId: 'datadoggy-43c89',
    authDomain: 'datadoggy-43c89.firebaseapp.com',
    storageBucket: 'datadoggy-43c89.firebasestorage.app',
    measurementId: 'G-SC4QRLF9V6',
  );
}
