name: dog_training_app
description: A Flutter app for dog training.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.5.1 # เวอร์ชันล่าสุดสำหรับการเล่นวิดีโอ
  firebase_core: ^3.10.0 # ใช้ Firebase Core ล่าสุด
  cloud_firestore: ^5.6.1 # Firestore ล่าสุด
  firebase_auth: ^5.5.1 # Authentication ล่าสุด
  firebase_storage: ^12.4.0 # สำหรับอัปโหลดไฟล์/รูปภาพ
  firebase_messaging: ^15.2.0 # สำหรับ Push Notification





flutter:
  assets:
    - assets/images/
    - assets/videos/
    - assets/images/doggy_logo.png
    - assets/images/dog_profile.png

