name: dog_training_app
description: A Flutter app for dog training.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.5.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/
