name: dog_training_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  image_picker: ^1.1.2
  flutter:
    sdk: flutter
  video_player: ^2.5.1
  firebase_core: ^3.10.0
  cloud_firestore: ^5.6.1
  firebase_auth: ^5.5.1
  firebase_storage: ^12.4.0
  firebase_messaging: ^15.2.0
  webview_flutter: ^4.4.4
  webview_flutter_web: ^0.2.2
  youtube_player_flutter: ^9.1.1
  audioplayers: ^6.4.0
  flutter_sound: ^9.28.0
  cupertino_icons: ^1.0.8
  
  # เพิ่ม dependencies สำหรับ Gemini API chatbot
  http: ^1.1.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  flutter_markdown: ^0.6.18
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/doggy_logo.png
    - assets/images/dog_profile.jpg
    - assets/images/whistle.png
    - assets/images/clicker.png
    - assets/images/dog_profile.png
    - assets/sounds/clicker_sound.mp3
    - assets/sounds/Whistle.mp3