name: dog_training_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  image_picker: ^1.1.2
  flutter:
    sdk: flutter
  video_player: ^2.5.1
  firebase_core: ^3.10.0
  cloud_firestore: ^5.6.1
  firebase_auth: ^5.5.1
  firebase_storage: ^12.4.0
  firebase_messaging: ^15.2.0
  webview_flutter: ^4.4.4
  webview_flutter_web: ^0.2.2
  audioplayers: ^6.4.0
  flutter_sound: ^9.28.0
  cupertino_icons: ^1.0.8
  youtube_player_iframe: ^5.1.2
  flutter_dotenv: ^5.1.0
  http: ^1.1.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  flutter_markdown: ^0.6.18
  intl: ^0.18.1

  
  cached_network_image: ^3.3.1    # สำหรับ cache รูปภาพจาก Cloudinary
  crypto: ^3.0.3                  # สำหรับ generate signature สำหรับ Cloudinary
  flutter_cache_manager: ^3.3.1   # ช่วยจัดการ cache
  
  
  shimmer: ^3.0.0                 # Loading animation สวยๆ
  pull_to_refresh: ^2.0.0         # Pull to refresh
  flutter_staggered_grid_view: ^0.7.0  # Grid layout สำหรับแสดงรูป
  photo_view: ^0.14.0             # Image viewer แบบ zoom ได้

  image: ^4.1.3              # สำหรับประมวลผลรูปภาพ
  path_provider: ^2.1.1      # สำหรับ temporary directory
  path: ^1.8.3         
  
  
  chewie: ^1.7.5                  # Video player ที่ดีกว่า video_player
  
  
  flutter_local_notifications: ^17.2.1  # Local notifications
  
  
  permission_handler: ^11.3.1     # จัดการ permissions

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/doggy_logo.png
    - assets/images/dog_profile.jpg
    - assets/images/whistle.png
    - assets/images/clicker.png
    - assets/images/dog_profile.png
    - assets/sounds/clicker_sound.mp3
    - assets/sounds/Whistle.mp3
    - .env